// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LnOFl0fiMVWoGwHo6h79o6owH7JtVYc',
    appId: '1:700074478728:web:85b3717277a97ac815a33d',
    messagingSenderId: '700074478728',
    projectId: 'chatapplication-ecff3',
    authDomain: 'chatapplication-ecff3.firebaseapp.com',
    storageBucket: 'chatapplication-ecff3.firebasestorage.app',
    measurementId: 'G-YGBYDELKBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LmTHF5ROw6_3kzeUT0JNIKIBiQDKmQk',
    appId: '1:700074478728:android:a43a46453bc8f2c715a33d',
    messagingSenderId: '700074478728',
    projectId: 'chatapplication-ecff3',
    storageBucket: 'chatapplication-ecff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97q_Iv8Qsj7-65ub-YqeRfRTuZKN8W2w',
    appId: '1:700074478728:ios:6086aec1860df41515a33d',
    messagingSenderId: '700074478728',
    projectId: 'chatapplication-ecff3',
    storageBucket: 'chatapplication-ecff3.firebasestorage.app',
    iosBundleId: 'chatapplication.com.chatapplication',
  );
}
